---
- name: Configure bind static zones
  ansible.builtin.template:
    src: 'zones/{{ item }}'
    dest: /var/named/data/{{ item }}
    lstrip_blocks: true
    force: true
    owner: named
    group: named
    mode: '0660'
  notify: Reload service named
  loop: '{{ bind_static_zone_templates }}'

- name: Configure bind dynamic zones
  ansible.builtin.template:
    src: 'zones/{{ item }}'
    dest: /var/named/dynamic/{{ item }}
    lstrip_blocks: true
    force: false
    owner: named
    group: named
    mode: '0660'
  notify: Reload service named
  loop: '{{ bind_dynamic_zone_templates }}'

- name: Configure bind
  ansible.builtin.template:
    src: '{{ bind_profile }}.conf'
    dest: /etc/named.conf
    lstrip_blocks: true
    owner: root
    group: named
    mode: '0640'
    validate: /usr/sbin/named-checkconf -z %s
  notify: Reload service named

- name: Enable and start service named
  ansible.builtin.systemd_service:
    name: named.service
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
